project_id = "tzfykqbulbkcdesjlapy"

[functions.execute-trades]
verify_jwt = false

[functions.generate-wallet]
verify_jwt = false

[functions.simulate-trades]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.withdraw-sol]
verify_jwt = false

[functions.public-api]
verify_jwt = false
